server:
  port: 8080
  undertow:
    threads:
      worker: 10
      io: 2
  jpa:
    properties:
      jakarta: # Scrip para geração de migration
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: update
              create-target: src/main/resources/db/hibernate/db_create.sql
              drop-target: src/main/resources/db/hibernate/db_drop.sql
              update-target: src/main/resources/db/hibernate/db_update.sql
postgres:
  url: localhost:5432
  username: postgres
  password: postgres
  schema: core_app
configs:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}
    allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS,PATCH}
    allowed-headers: ${CORS_ALLOWED_HEADERS:Authorization,Content-Type,Accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers}
    exposed-headers: ${CORS_EXPOSED_HEADERS:Authorization,Content-Type,Accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers}
    max-age: ${CORS_MAX_AGE:3600}
  keycloak:
    realm: Project_Core
    auth-server-url: http://localhost:9090
    auth-server-url-admin: http://localhost:9090/admin/realms/${configs.keycloak.realm}
    client-id: project-core-rest-api
    client-secret: ${CLIENT_SECRET:t44A1Kq2CVplt012Kva51KUxNdQxgpA5}
    admin-user: project-core-rest-api
    admin-password: rDRZmvZM6F1DFK37L6OYMZZ1veGZIYJU
  bucket:
    region:
    name:
    access-key:
    secret-key: