version: '3.7'
services:
  postgres:
    container_name: project_core_postgres
    image: postgres:latest
    restart: always
    tty: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: core_app
      PGDATA: /data/postgres
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./keycloak/create-keycloak-database.sql:/docker-entrypoint-initdb.d/create-keycloak-database.sql
    ports:
      - 5432:5432
    networks:
      - project_core_network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      retries: 5
      start_period: 10s

  keycloak:
    container_name: project_core_keycloak
    image: quay.io/keycloak/keycloak:26.1.4
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/core_app_keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    ports:
      - 9090:8080
    command: start-dev --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false
    volumes:
      - .docker/keycloak-themes:/opt/keycloak/themes
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - project_core_network

networks:
  project_core_network: